# Generated by Django 2.2.7 on 2019-12-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='squirrel',
            fields=[
                ('Unique_Squirrel_ID', models.CharField(blank=True, default=None, max_length=14, primary_key=True, serialize=False)),
                ('Longitude', models.DecimalField(blank=True, decimal_places=13, default=None, max_digits=1000, null=True)),
                ('Latitude', models.DecimalField(blank=True, decimal_places=13, default=None, max_digits=1000, null=True)),
                ('Shift', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2, null=True)),
                ('Date', models.CharField(blank=True, default=0, max_length=20)),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], max_length=20, null=True)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], default=None, max_length=8, null=True)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], default=None, max_length=100, null=True)),
                ('Specific_Location', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Running', models.BooleanField(blank=True, default=None, null=True)),
                ('Chasing', models.BooleanField(blank=True, default=None, null=True)),
                ('Climbing', models.BooleanField(blank=True, default=None, null=True)),
                ('Eating', models.BooleanField(blank=True, default=None, null=True)),
                ('Foraging', models.BooleanField(blank=True, default=None, null=True)),
                ('Other_Activities', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Kuks', models.BooleanField(blank=True, default=None, null=True)),
                ('Quaas', models.BooleanField(blank=True, default=None, null=True)),
                ('Moans', models.BooleanField(blank=True, default=None, null=True)),
                ('Tail_flags', models.BooleanField(blank=True, default=None, null=True)),
                ('Tail_twitches', models.BooleanField(blank=True, default=None, null=True)),
                ('Approaches', models.BooleanField(blank=True, default=None, null=True)),
                ('Indifferent', models.BooleanField(blank=True, default=None, null=True)),
                ('Runs_from', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
    ]
